// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbesxgkkplveteqzldng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZXN4Z2trcGx2ZXRlcXpsZG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3OTQ5NDYsImV4cCI6MjA0ODM3MDk0Nn0.gNvDms8NbiNRJ4eRN0IyOvxfkzGHE4aRYqnZ9hOwFjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);